name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          VITE_APP_BASE_URL: "/portfolio"
          VITE_BASE: "/portfolio/"
          PUBLIC_URL: "/portfolio"
          BASE_URL: "/portfolio/"
          NODE_ENV: "production"
          VITE_PUBLIC_PATH: "/portfolio/"

      - name: Setup GitHub Pages files
        run: |
          cp dist/public/index.html dist/public/404.html
          touch dist/public/.nojekyll
          echo "/* /index.html 200" > dist/public/_redirects
          # Update asset paths in HTML files
          find dist/public -type f -name "*.html" -exec sed -i 's|"/assets|"/portfolio/assets|g' {} +
          # Add base tag if not present
          find dist/public -type f -name "*.html" -exec sed -i 's|<head>|<head><base href="/portfolio/"/>|' {} +
          # Update asset paths in JS files
          find dist/public -type f -name "*.js" -exec sed -i 's|"/assets|"/portfolio/assets|g' {} +
          # Handle source maps if they exist
          find dist/public -type f -name "*.map" -exec sed -i 's|"/assets|"/portfolio/assets|g' {} +
          # Ensure index.html is properly configured
          cat > dist/public/index.html << EOL
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Portfolio - Jagan Pazhaniyandi</title>
    <meta name="description" content="Technology consulting and engineering management portfolio of Jagan Pazhaniyandi" />
    <base href="/portfolio/" />
    <script type="text/javascript">
      // Single Page Apps for GitHub Pages
      // MIT License
      // https://github.com/rafgraph/spa-github-pages
      (function(l) {
        if (l.search[1] === '/' ) {
          var decoded = l.search.slice(1).split('&').map(function(s) { 
            return s.replace(/~and~/g, '&')
          }).join('?');
          window.history.replaceState(null, null,
              l.pathname.slice(0, -1) + decoded + l.hash
          );
        }
      }(window.location))
    </script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/portfolio/assets/index-BwHb7hv3.js"></script>
    <link rel="stylesheet" href="/portfolio/assets/index-CZMyz56N.css">
  </body>
</html>
EOL

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4